#!/bin/sh

start()
{
	if [ ! -z "$1" ]; then
		DDIR="$1"
	elif [ -d ~/Downloads ]; then
		DDIR=~/Downloads
	else
		DDIR=$(pwd)
	fi

	TASK=$DDIR/aria.task
	if [ ! -r $TASK ]; then touch $TASK; fi

	ARIA2C=$(cd "${0%/*}"; pwd)/aria2c
	if [ ! -x $ARIA2C ]; then ARIA2C=aria2c; fi

	#XOPT='--split=100 --max-connection-per-server=100 --timeout=1 --max-tries=0 --user-agent=netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia'
	$ARIA2C -D -d $DDIR -c -i $TASK --save-session=$TASK --enable-rpc --rpc-listen-all --rpc-allow-origin-all --file-allocation=falloc --disable-ipv6
}

case "$1" in
	start)
		echo "Starting aria2c daemon..."
		start $2
		;;
	stop)
		echo "Shutting down aria2c daemon..."
		killall aria2c
		;;
	restart)
		killall aria2c
		sleep 1
		start $2
		;;
	'')
		echo "Aria2c helper by Yonsm"
		echo
		echo "Usage: $0 [start|stop|restart|<DIR>] [DIR]"
		echo
		;;
	*)
		start $1
		;;
esac

# Aria
#aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "xxxx" --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=; pcsett=" "https://d.pcs.baidu.com/"
