#!/bin/sh
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
#chown -R admin:users .
find . -type f -name "._*" -exec rm -f {} \;
find . -type f -name ".DS_Store" -exec rm -f {} \;
find . -type f -name ".AppleDouble" -exec rm -f {} \;
find . -name ".*"
