#!/bin/sh

if [ "$1" == 'mod' ]; then
	find . -type f -exec chmod 644 {} \;
	find . -type d -exec chmod 755 {} \;
	chown -R admin:users .
elif [ "$1" == 'all' ]; then
	mdutil -i off `pwd`
	# sudo mdutil -a -i off
	# sudo touch .metadata_never_index
	rm -rf .*
else
	find . -type f -name "._*" -exec rm -f {} \;
	find . -type f -name ".DS_Store" -exec rm -f {} \;
	find . -type f -name ".AppleDouble" -exec rm -f {} \;
	find . -name ".*"
fi
