#!/bin/sh
if [ $# = 0 ]; then
    echo "Usage: $0 MountPoint|DiskIdentifier|DeviceNode|UUID"
else
    INFO=`diskutil info $1`
    NODE=`echo "$INFO" | grep "Device Node:" | awk '{print $3}'`
    FS=`echo "$INFO" | grep "File System Personality:" | awk '{print $4}'`
    if [ "$FS" != "NTFS" ]; then
        echo "$INFO"
        echo "$NODE $FS is not NTFS!"
        exit 1
    fi
    NAME=`echo "$INFO" | grep "Volume Name:" | perl -ne 'print $1 if /.*Volume Name:\s*(\S.*)/s'
    if [ -z "$NAME" ]; then
        NAME=NTFS
    fi
    sudo umount $NODE
    sudo mkdir /Volumes/$NAME
    sudo mount_ntfs -o rw,nobrowse $NODE /Volumes/$NAME
    open /Volumes/$NAME
fi
