#!/bin/sh

APPS="AliLangX AppDelete V2RayX ShadowsocksX"

SetLSUI()
{
    for APP in $APPS; do
        if [ -d ~/Applications/Utilities/$APP.app ]; then
            plutil -replace LSUIElement -bool $1 ~/Applications/Utilities/$APP.app/Contents/Info.plist
        fi
    done
}

SetLSUI false

defaults write com.apple.dock ResetLaunchPad -bool true
killall Dock

sleep 5
SetLSUI true
