#!/bin/sh
Pictures="$1"

# Check
if [ ! -d "$Pictures" ]; then
	echo "Pictures dir not exist"
	exit 1
fi
cd "$Pictures"


qren()
{
	for PIC in `ls "$1"|tr " " "?"`
	do
		PIC=`echo "$PIC"|tr "?" " "`
		PIC2=`echo "$PIC"|tr " " "_"`
		if [[ "$PIC" != "$PIC2" ]]; then
			mv -n "$1/$PIC" "$1/$PIC2"
		fi
	done
}

qmove()
{
	if [ -z $2 ]; then
		QYEAR=2010
	else
		QYEAR=$2
	fi
	for PIC in `ls "$1"|tr " " "?"`
	do
		PIC=`echo "$PIC"|tr "?" " "`
		YEAR=${PIC%%"-"*}
		if [ $YEAR -ge 2000 ] 2>/dev/null && [ $YEAR -lt $QYEAR ] 2>/dev/null; then
			QDIR=$YEAR
		elif [ $YEAR -ge $QYEAR ] 2>/dev/null && [ $YEAR -le 2099 ] 2>/dev/null; then
			MONTH=${PIC#*"-"}
			MONTH=${MONTH:0:2}
			if [ $MONTH -ge 1 ] 2>/dev/null && [ $MONTH -le 3 ] 2>/dev/null; then
				QDIR=$YEAR.Q1
			elif [ $MONTH -ge 4 ] 2>/dev/null && [ $MONTH -le 6 ] 2>/dev/null; then
				QDIR=$YEAR.Q2
			elif [ $MONTH -ge 7 ] 2>/dev/null && [ $MONTH -le 9 ] 2>/dev/null; then
				QDIR=$YEAR.Q3
			elif [ $MONTH -ge 10 ] 2>/dev/null && [ $MONTH -le 12 ] 2>/dev/null; then
				QDIR=$YEAR.Q4
			else
				echo "ERROR: Unexception month $MONTH: $1/$PIC"
				continue
			fi
		else
			echo "ERROR: Unexception year $YEAR: $1/$PIC"
			continue
		fi
		[ ! -d $QDIR ] && mkdir $QDIR
		PIC2=`echo "$PIC"|tr " " "_"`
		mv -n "$1/$PIC" "$QDIR/$PIC2"
	done
	rmdir "$1"
}
		
[ -d "2000.00 头像" ] && rm -rf "2000.00 头像"
[ -d "2016.04 装修" ] && rm -rf "2016.04 装修"
[ -f "2020.03/2020.03.17 170601.mp4" ] && mv "2020.03/2020.03.17 170601.mp4" "2020.03/2020-03-17.170601.mp4"

qdir()
{
	case "$1" in
		20??|*.Q1|*.Q2|*.Q3|*.Q4)
			echo "RENAME: $1"
			#qren "$1"
			;;
		20*)
			echo "MOVE: $1"
			qmove "$1" "$2"
			;;
		*)
			echo "SKIP: $1"
			;;
	esac
	return 0
}

for DIR in `ls|tr " " "?"`
do
	echo "$DIR" >> /tmp/test.txt
	DIR=`echo "$DIR"|tr "?" " "`
	qdir "$DIR" "$2"
done

