#!/bin/sh
CDIR=$(cd "${0%/*}"; pwd)
PATH=$CDIR:$PATH

RENAME()
{
	SRC="$1/$2"
	DST="$1/$3.$4"
	if [ "$SRC" != "$DST" ]; then
		if [ -f "$DST" ]; then
			RENAME "$1" "$2" "$3_" "$4" "$5" "$6"
		else
			echo "$5: $2 => $3.$4"
			if [ "$6" != "-" ]; then
				mv "$SRC" "$DST"
				if [ -f "$1/.thumb.$2.jpg" ]; then
					echo "$5: .thumb.$2.jpg => .thumb.$3.$4.jpg"
					mv "$1/.thumb.$2.jpg" "$1/.thumb.$3.$4.jpg"
				fi
			fi
		fi
	else
		echo "$5: $2 => SAME"
	fi
}

REFILE()
{
	SDIR="$1"
	FILE="$2"
	TEST="$3"
	EXT=${FILE##*.}
	EXT=`echo $EXT | tr "[:upper:]" "[:lower:]"`

	if [ "$EXT" = "jpg" ] || [ "$EXT" = "jpeg" ]; then
		DATE=`jhead "$SDIR/$FILE" | grep "Date/Time"`
		if [ -z "$DATE" ]; then
			NAME=""
		else
			NAME="`echo ${DATE:15:10} | tr : -` `echo ${DATE:26} | tr -d :`"
		fi
		RESULT="EXIF"
		[ "$EXT" = "jpeg" ] && EXT=jpg
	elif [ "$EXT" = "png" ] || [ "$EXT" = "gif" ] || [ "$EXT" = "mov" ] || [ "$EXT" = "mp4" ] || [ "$EXT" = "avi" ] || [ "$EXT" = "heic" ]; then
		NAME=""
	else
		return 1
	fi

	if [ -z "$NAME" ]; then
		if [ "$TEST" != "!" ] && [ ${#FILE} -eq 21 ] && [ "${FILE:4:1}" == "-" ] && [ "${FILE:7:1}" == "-" ] && [ "${FILE:10:1}" == " " ]; then
			echo "KEEP: $FILE"
			return 2
		else
			if [ "$TEST" != "!" ] && [ ${#FILE} -ge 23 ] && [ "${FILE:4:1}" == "-" ] && [ "${FILE:7:1}" == "-" ] && [ "${FILE:10:1}" == "_" ] && [ "${FILE:13:1}" == "-" ] && [ "${FILE:16:1}" == "-" ]; then
				NAME="${FILE:0:10} ${FILE:11:2}${FILE:14:2}${FILE:17:2}"
				RESULT="NAME"
			else
				if [ "${OSTYPE:0:6}" == "darwin" ]; then
					NAME=`stat -f "%Sm" -t "%Y-%m-%d %H%M%S" "$SDIR/$FILE"`
				else
					DATE=`stat -c "%y" "$SDIR/$FILE" | cut -c1-32`
					NAME=`date "+%Y-%m-%d %H%M%S" -d "$DATE"`
				fi
				RESULT="STAT"
			fi
		fi
	fi

	if [ ! -z "$NAME" ]; then
		RENAME "$SDIR" "$FILE" "${NAME/ /_}" "$EXT" "$RESULT" "$TEST"
	else
		echo "FAIL: $FILE"
	fi
}

if [ -f "$1" ]; then
	REFILE "`dirname "$1"`" "`basename "$1"`" "$2"
	exit 0
fi

if [ -z "$1" ]; then
	DIR="."
else
	DIR="$1"
fi 

for FILE in `ls "$DIR"|tr " " "?"`
do
	FILE=`echo $FILE|tr "?" " "`
	REFILE "$DIR" "$FILE" "$2"
done
