#!/bin/sh
CDIR=$(cd "${0%/*}"; pwd)

echo "$CDIR/bin" | sudo tee /etc/paths.d/tools.admin.diy
echo "admin ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers

sudo spctl --master-disable

#defaults write com.apple.iTunes DeviceBackupsDisabled -bool YES
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
defaults write com.apple.iTunes AutomaticDeviceBackupsDisabled -bool true

#$CDIR/RAMDISK.sh

exit

# Chrome + Baidu https://github.com/acgotaku/BaiduExporter
#cd /Volumes/RAM && git clone https://github.com/CodeTips/BaiduNetdiskPlugin-macOS.git && cd /Volumes/RAM/BaiduNetdiskPlugin-macOS/Other && sed 's/\/Applications/\/Users\/admin\/Applications/g' Install.sh | sh

# Speed Test
curl -o $CDIR/speedtest https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x $CDIR/speedtest

# Brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update

pip3 install esptool
