#!/bin/sh
CDIR=$(cd "${0%/*}"; pwd)

echo "$CDIR" | sudo tee /etc/paths.d/net.yonsm.macx

sudo grep "admin ALL=(ALL) NOPASSWD: ALL" /etc/sudoers >/dev/null 2>&1
if [ $? = 1 ]; then
    echo "admin ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
fi

sudo spctl --master-disable

defaults write com.apple.iTunes DeviceBackupsDisabled -bool YES
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
defaults write com.apple.iTunes AutomaticDeviceBackupsDisabled -bool true

#$CDIR/XRamDisk

exit


# Speed Test
cd $CDIR
curl -o speedtest https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest

# Brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update

brew install scrcpy

# Python
mkdir ~/.pip
cat << \EOF > ~/.pip/pip.conf
[global]
index-url=http://mirrors.aliyun.com/pypi/simple/
[install]
trusted-host=mirrors.aliyun.com
EOF

pip3 install esptool miservice

# Sublime
# +Package Control: Command+Shift+P
#   +ChineseLocalizations
#   +ConvertToUTF8
#   +Codec33
#   +JsFormat
#   +Pretty JSON
# Settings
#   "rulers": [80,120,160,200],
#   "word_wrap": "false",
#   "update_check": false,
#   "translate_tabs_to_spaces": true,
#   "trim_trailing_white_space_on_save": true,
# Host
#	搜索16进制 97 94 0D 00 改为 00 00 00 00
echo "0.0.0.0 license.sublimehq.com" | sudo tee -a /etc/hosts
echo "0.0.0.0 45.55.255.55" | sudo tee -a /etc/hosts
echo "0.0.0.0 45.55.41.223" | sudo tee -a /etc/hosts
echo "127.0.0.1 www.sublimetext.com" | sudo tee -a /etc/hosts
echo "127.0.0.1 sublimetext.com" | sudo tee -a /etc/hosts
echo "127.0.0.1 sublimehq.com" | sudo tee -a /etc/hosts
echo "127.0.0.1 telemetry.sublimehq.com" | sudo tee -a /etc/hosts
echo

# SN
cat << \EOF
# Sublime
—– BEGIN LICENSE —–
Mifeng User
Single User License
EA7E-1184812
C0DAA9CD 6BE825B5 FF935692 1750523A
EDF59D3F A3BD6C96 F8D33866 3F1CCCEA
1C25BE4D 25B1C4CC 5110C20E 5246CC42
D232C83B C99CCC42 0E32890C B6CBF018
B1D4C178 2F9DDB16 ABAA74E5 95304BEF
9D0CCFA9 8AF8F8E2 1E0A955E 4771A576
50737C65 325B6C32 817DCB83 A7394DFA
27B7E747 736A1198 B3865734 0B434AA5
—— END LICENSE ——

#Axure
zedex.cn
xpU4wqREqR6MNDjj957APLHET1GwFV1d6bMjkconScgt01Z2nSwH1pz55FQs5MIh

#AppDelete
AD-V845-I172-R956-B601

PlistEdit
PLEDPRO095-42E7-REKA-M4H4-1309-1405

#Pacifist
MacXMacX
4nbSTd3G6C-2bS2quo1of-AIC

#VMWare
4C21U-2KK9Q-M8130-4V2QH-CF810

#Proxifier
P427L-9Y552-5433E-8DSR3-58Z68

# https://www.zzzmode.com/mytools/charles/
Mac OS
6BACE69077E6DA3993
EOF

# VS Code
#   +PlatformIO
cat << \EOF > ~/Library/Application\ Support/Code/User/settings.json
{
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.detectIndentation": true,
    "editor.insertSpaces": false,
    "editor.minimap.enabled": false,
    "editor.useTabStops": true,
    "html.format.wrapLineLength": 160,
    "prettier.endOfLine": "lf",
    "prettier.htmlWhitespaceSensitivity": "strict",
    "prettier.printWidth": 160,
    "prettier.semi": false,
    "prettier.singleQuote": true,
    "prettier.tabWidth": 4,
    "prettier.useTabs": true,
    "python.autoComplete.addBrackets": true,
    "python.pythonPath": "/usr/bin/python3",
    "workbench.startupEditor": "newUntitledFile",
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Args": ["--max-line-length=200"]
}
EOF
