#!/bin/sh

if [ -z "$WIRESHARK_APP_DIR" ] ; then
    WIRESHARK_APP_DIR="/Applications/Utilities/Wireshark.app"
    if [ ! -d "$WIRESHARK_APP_DIR" ] ; then
        WIRESHARK_APP_DIR="/Users/admin/Applications/Utilities/Wireshark.app"
    fi
fi

if [ ! -d "$WIRESHARK_APP_DIR" ] ; then
	WIRESHARK_APP_DIR=`mdfind "kMDItemCFBundleIdentifier == 'org.wireshark.Wireshark'" | head -n 1`
fi

if [ ! -d "$WIRESHARK_APP_DIR" ] ; then
	echo "Wireshark doesn't appear to be located at $WIRESHARK_APP_DIR."
	echo "Please set WIRESHARK_APP_DIR to its proper location and try again."
	exit 1
fi


# opkg install libc libpcap tcmpdump

APP_PATH="$WIRESHARK_APP_DIR/Contents/MacOS/WireShark"
if [[ $1 == *@* ]]; then
    if [ -z $2 ]; then
        IF=br0
    else
        IF=$2
    fi
    if [ -z $3 ]; then
        DUMP=tcpdump
    else
        DUMP=$3
    fi
    if [ -z $4 ]; then
        HOST=
    else
        HOST="and host $4"
    fi
    ssh $1 "$DUMP -s 0 -U -n -i $IF -w - not port 22 $HOST" | "$APP_PATH" -k -i -
else
    sudo chmod 666 /dev/bpf*
    echo exec "$APP_PATH" "$@"
fi
